/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 248670e01440182c1cfa9c2beb4ac10e)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	OIDC_ISSUER: string;
	OIDC_CLIENT_ID: string;
	OIDC_AUDIENCE: string;
	WALLET_NETWORK: string;
	SIGNER_MODE: string;
	CDP_API_KEY_ID: string;
	CDP_API_KEY_SECRET: string;
	CDP_WALLET_SECRET: string;
	CDP_PROJECT_ID: string;
	MOCK_SIGNER_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "OIDC_ISSUER" | "OIDC_CLIENT_ID" | "OIDC_AUDIENCE" | "WALLET_NETWORK" | "SIGNER_MODE" | "CDP_API_KEY_ID" | "CDP_API_KEY_SECRET" | "CDP_WALLET_SECRET" | "CDP_PROJECT_ID" | "MOCK_SIGNER_PRIVATE_KEY">> {}
}
