/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env-file=.dev.vars.example --include-runtime=false` (hash: 410f8d1a9fde152d2a0fc22395ecb79a)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: string;
	OIDC_ISSUER: string;
	OIDC_CLIENT_ID: string;
	WALLET_NETWORKS: string;
	PAYMENT_NETWORKS: string;
	SIGNER_MODE: string;
	BASE_RPC_URL: string;
	BASE_SEPOLIA_RPC_URL: string;
	POLYGON_RPC_URL: string;
	ARBITRUM_RPC_URL: string;
	WORLD_RPC_URL: string;
	WORLD_SEPOLIA_RPC_URL: string;
	SOLANA_RPC_URL: string;
	SOLANA_DEVNET_RPC_URL: string;
	CDP_API_KEY_ID: string;
	CDP_API_KEY_SECRET: string;
	CDP_WALLET_SECRET: string;
	CDP_PROJECT_ID: string;
	MOCK_SIGNER_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./server/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "OIDC_ISSUER" | "OIDC_CLIENT_ID" | "WALLET_NETWORKS" | "PAYMENT_NETWORKS" | "SIGNER_MODE" | "BASE_RPC_URL" | "BASE_SEPOLIA_RPC_URL" | "POLYGON_RPC_URL" | "ARBITRUM_RPC_URL" | "WORLD_RPC_URL" | "WORLD_SEPOLIA_RPC_URL" | "SOLANA_RPC_URL" | "SOLANA_DEVNET_RPC_URL" | "CDP_API_KEY_ID" | "CDP_API_KEY_SECRET" | "CDP_WALLET_SECRET" | "CDP_PROJECT_ID" | "MOCK_SIGNER_PRIVATE_KEY">> {}
}
